In [1]:
#Numpy

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy  as np

In [8]:
# Creating Aarrays (1D)

In [9]:
sample_array = np.array([1,2,3,4])

In [10]:
sample_array

array([1, 2, 3, 4])

In [11]:
# 2D Array (Matrix)

In [12]:
sample_array2 = np.array([[1,2],[3,4]])

In [13]:
sample_array2

array([[1, 2],
       [3, 4]])

In [14]:
# 3D Array(Tensor)

In [17]:
sample_array3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])    

In [18]:
sample_array3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
# Dimension
# 0 - D (Scalar) - Number
# 1 - D (Vector) - List
# 2 - D (Matrix) - A Table With Rows And Columns
# 3 - D (Tensor) - A Stack Of Tables

In [21]:
sample_array3 = np.array([
    [[91,92],[93,94]],
    [[95,96],[97,98]]
])    

In [22]:
sample_array3

array([[[91, 92],
        [93, 94]],

       [[95, 96],
        [97, 98]]])

In [23]:
# Array Properties

In [45]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [46]:
sample_array2 = np.array(

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
# Shape

In [48]:
sample_array.shape

(2, 3)

In [49]:
sample_array.ndim

2

In [50]:
sample_array.size

6

In [51]:
sample_array.dtype

dtype('int64')

In [65]:
sample_array2=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [66]:
sample_array2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
sample_array2.shape

(2, 2, 3)

In [68]:
sample_array2.ndim

3

In [71]:
sample_array2.size

12

In [72]:
sample_array2.dtype

dtype('int64')

In [75]:
sample_array = np.array([[0,0,0],[0,0,0]])

In [76]:
sample_array

array([[0, 0, 0],
       [0, 0, 0]])

In [77]:
sample_array2 = np.array([[1,1,1,],[1,1,1]])

In [79]:
sample_array2

array([[1, 1, 1],
       [1, 1, 1]])

In [80]:
# Spacial Array

In [81]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [83]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [84]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [88]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [89]:
# 1 D

In [90]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [91]:
a

array([1, 2, 3])

In [92]:
b

array([4, 5, 6])

In [94]:
a + b

array([5, 7, 9])

In [99]:
a - b


array([-3, -3, -3])

In [100]:
a * b

array([ 4, 10, 18])

In [101]:
a / b

array([0.25, 0.4 , 0.5 ])

In [102]:
# Mathematical Function

In [127]:
sample_array = np.array([1,4,9])

In [128]:
sample_array

array([1, 4, 9])

In [129]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [130]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [131]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [132]:
# statistical functions

In [135]:
sample_array = np.array([1,2,3,4,5,6,7,8,9])

In [136]:
sample_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
np.mean(sample_array)

np.float64(5.0)

In [138]:
np.median(sample_array)

np.float64(5.0)

In [140]:
np.std(sample_array)

np.float64(2.581988897471611)

In [141]:
np.min(sample_array)

np.int64(1)

In [142]:
np.max(sample_array)

np.int64(9)

In [143]:
sample_array = np.array([68,67,58,1003])

In [144]:
sample_array

array([  68,   67,   58, 1003])

In [145]:
np.mean(sample_array)

np.float64(299.0)

In [146]:
np.median(sample_array)

np.float64(67.5)

In [147]:
np.std(sample_array)

np.float64(406.47324635208156)

In [148]:
np.min(sample_array)

np.int64(58)

In [149]:
np.max(sample_array)

np.int64(1003)

In [152]:
# Flattening

In [153]:
sample_array = np.array([[1,2],[3,4,]])

In [154]:
sample_array

array([[1, 2],
       [3, 4]])

In [155]:
sample_array.flatten()

array([1, 2, 3, 4])

In [157]:
sample_array = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [158]:
sample_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [159]:
sample_array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [160]:
a = np.array([1,2])
b = np.array([3,4])

In [161]:
a

array([1, 2])

In [162]:
b

array([3, 4])

In [169]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [170]:
sample_array = np.array([1,2,3,4])

In [171]:
sample_array

array([1, 2, 3, 4])

In [174]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [175]:
# Random Module

In [176]:
np.random.rand(3)

array([0.87525526, 0.21131311, 0.20838541])

In [177]:
np.random.rand(10)

array([0.64718427, 0.35743328, 0.13709399, 0.44341339, 0.2581509 ,
       0.38633755, 0.63414699, 0.3423964 , 0.11433605, 0.70171359])

In [178]:
np.random.randint(1,100,10)

array([ 7, 92, 12, 46, 65,  5, 88, 64, 73, 31], dtype=int32)

In [181]:
sample_array = np.array([[1,2],[3,4]])

In [182]:
sample_array

array([[1, 2],
       [3, 4]])

In [183]:
np.sum(sample_array, axis=0)

array([4, 6])

In [187]:
np.sum(sample_array, axis=1)

array([3, 7])

In [195]:
sample_array = np.array([[1,np.nan,3]])

In [196]:
sample_array

array([[ 1., nan,  3.]])

In [197]:
np.isnan(sample_array)

array([[False,  True, False]])

In [200]:
sample_array2 = np.array([[1,np.nan,3],[2, np.nan,5]])

In [202]:
sample_array2

array([[ 1., nan,  3.],
       [ 2., nan,  5.]])

In [204]:
np.isnan(sample_array2)

array([[False,  True, False],
       [False,  True, False]])

In [205]:
sample_array = np.arange(6)

In [206]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [209]:
reshaped = sample_array.reshape(2,3)

In [210]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])